### ISSUE TITLE
Request to expand user profile information

### ISSUE THREAD

**Issue by Aguza5** [decide-moltres/decide#6]
**Problem description**
Voting module needs to expand the user profile information to implement the senate elections functionality.

**Solution description**

Add the following attributes to the user profile:
 
-Province: It is the Province where this person lives and has the following values: Sevillistan, Huelvistan, Cadistan

-Employment: It's the position that person has in the political party. This position is optional  and has the following values: militant, baron, president and senator.

Modify the current attributes:

-In sex, remove sex "other" 

-In political party, make it optional

**Comment by rayo329** [comment]
Issue solved in the following commits: https://github.com/decide-moltres/decide-Auth/commit/7d713684951c0b06f892111253305d474b0d3578
https://github.com/decide-moltres/decide-votacion/commit/3805f9986caef7e16fe949990da1e597fda45e57

Soon™ authentification will bring those changes to this repository.
